### ISSUE TITLE
STL Files (Question)

### ISSUE THREAD

**Issue by fefifofums** [mgrl/photobooth-3d#1]
Hello,

Thank you for publishing your work. 

I don't have a copy of Solidworks.  Have you posted the STL files for this project any where?

**Comment by mgrl** [comment]
Hello, I did not post.
Slic3r nowadays accepts STP files so I prefer to export to STP.
Is this working for you or you can convert?

**Comment by fefifofums** [comment]
I see, that does work.  I just have to filter out all the superfluous objects.  Thank you!
